### ISSUE TITLE
Error generating build

### ISSUE THREAD

**Issue by luandro** [meshtastic/meshtastic-web#1]
On dev mode the app runs perfectly. But I get an error when trying to generate a build with `SNOWPACK_PUBLIC_DEVICE_IP=10.42.57.130 yarn build`:
```
[19:33:46] [snowpack] rimrafSafe(): /home/meshtastic/meshtastic-web/node_modules/@emotion/memoize/dist/memoize.browser.cjs.js outside of buildOptions.out /home/meshtastic/meshtastic-web/build
[19:33:46] [snowpack] Error: rimrafSafe(): /home/meshtastic/meshtastic-web/node_modules/@emotion/memoize/dist/memoize.browser.cjs.js outside of buildOptions.out /home/meshtastic/meshtastic-web/build
    at Object.deleteFromBuildSafe (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/util.js:76:15)
    at Object.runBuiltInOptimize (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/build/optimize.js:419:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.optimize (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/build/process.js:299:9)
    at async build (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/commands/build.js:18:5)
    at async Object.command (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/commands/build.js:35:9)
    at async cli (/home/meshtastic/meshtastic-web/node_modules/snowpack/lib/cjs/index.js:174:9)
```

**Comment by luandro** [comment]
Disabling bundle option on `snowpack.config.mjs` stops the error.

**Comment by sachaw** [comment]
Yes, I'm aware of this, it's a problem with `@emotion/memoize` there's a temp workaround by commenting out https://github.com/snowpackjs/snowpack/blob/c659b7c33bfb6ec995a279f99e890b5fddaee361/snowpack/src/util.ts#L62-L70
in your `node_modules` folder
